allowLineBreaksInTitles: false
color: indigo
description: null
fieldLayouts:
  f9704c19-a5d2-4cd1-85a9-684b34e886be:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:ce1daa1e-8e92-4aef-ae11-35f5d696c3bd'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-25T19:00:22+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 23ab57f9-640e-4064-8333-458692667dec # Bilder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce1daa1e-8e92-4aef-ae11-35f5d696c3bd
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: f9aa1517-b4ff-40f2-b0d5-e8f6c022c539
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-25T19:07:01+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 804989f5-8178-4b78-ae48-55ea6607711f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T19:15:59+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 11f840b0-e02b-470d-8a12-11e80446b819 # SVG Variante
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a89edef4-6efa-4e74-bad2-442452e8ddcb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T19:12:19+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: be9e472f-6557-47cc-8402-06b4027d587b # Abgerundet?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 148aa3a8-b477-46dd-8202-6b90028902aa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T19:03:38+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 74210a0e-fd21-4d35-ad82-89fd1c871a69 # Layout
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3125a0a-b524-4220-996e-9e2799884f1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T19:05:03+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 74210a0e-fd21-4d35-ad82-89fd1c871a69 # Layout
                  layoutElementUid: e3125a0a-b524-4220-996e-9e2799884f1d
                  operator: in
                  uid: 10f4ec94-109a-4618-b754-e11a501e6ce0
                  values:
                    - auto
                    - grid
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 1576f0ec-fbf0-46df-bdf5-c0b9a27c17a5 # Spalten
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49eb5768-2385-4acc-84ec-976f58968a3f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T19:08:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6707f2a7-b016-4641-aa2d-165292b7dfb1 # LÃ¼cke
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e0277b8-c21b-413b-a3be-ab79e216ea4a
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: b2fdd460-3d54-4197-b38a-88a39785b249
        userCondition: null
    thumbFieldKey: null
handle: imageGallery
hasTitleField: false
icon: images-user
name: Bilder
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Bilder
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
