color: null
description: null
fieldLayouts:
  1393f7bb-add0-4e8c-9671-e57f34296b56:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-19T14:34:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4df58b7b-bec5-4d25-894d-b73373a21fd6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T14:40:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46dc81ec-70cb-496a-98e9-65e6ca50b3d5 # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ba55312-40dd-47a9-91e1-5086a7f07de2
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 62fe8f86-3296-4b77-83e8-3238295a1d82
        userCondition: null
handle: link
hasTitleField: true
icon: null
name: Link
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
