color: null
description: null
fieldLayouts:
  d3e8200e-eb08-4b86-8d7d-8ded202268aa:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-19T14:26:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e5a0f5ba-c8ac-4d13-bc29-6d92e990019e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T15:39:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 73fc6da3-d133-4a74-affd-c06ae2ca7c3c # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90da2298-2421-44ce-a7d8-c53076f4141a
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1fc7fd73-223d-49ae-9f36-3cfd9b2af813
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-26T18:05:00+00:00'
            elementCondition: null
            heading: Suchmaschinen-Optimierung
            type: craft\fieldlayoutelements\Heading
            uid: 539b7976-f949-4c0b-a27a-89f10d84eeb9
            userCondition: null
          -
            dateAdded: '2025-12-26T18:05:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9f454419-a68a-4271-afa9-c4b736016383
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1b121ad-ab07-4745-a426-a3e90932d765
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T18:05:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 203d08b2-04c9-4069-910c-6def1a3c9f7f
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1198303d-abaf-443a-9c5b-72f039d6be13
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T18:05:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a65fe4d-8c4b-4f67-8c72-fb9f98cf3d52 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cce6616c-9409-4654-97af-cb306c8c280b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2c3d
        userCondition: null
handle: pages
hasTitleField: true
icon: book
name: Seiten
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
