color: null
description: null
fieldLayouts:
  7053b88e-ad36-4f0b-a96f-dcf1466480d6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-25T20:51:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: db0ef590-9ca1-4f8e-a409-d118f6fb3ad8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T21:14:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 02042204-6864-49bf-9cde-1cb1aa18da80 # Highlighted?
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0a940f3-ed2d-4b17-b07d-2de19cd7b800
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T21:07:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c748359f-b917-4760-be70-9ce67ca6ce7f # Features
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce6b1fd4-b235-4d29-b8c9-dee2c2a4bc7f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T21:09:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: price
            instructions: null
            label: Preis
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f132a6b1-db9d-421d-965d-808b25412ee4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-25T21:09:19+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: billingModel
            instructions: null
            label: Abrechnungsmodell
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 032e4d13-51b1-43c1-b763-4ebf98a97126
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 0d357833-faf8-4445-a92d-00562dd9915e
        userCondition: null
handle: price
hasTitleField: true
icon: money-bill-1
name: Preis
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
