allowLineBreaksInTitles: false
color: sky
description: null
fieldLayouts:
  7a81d751-eb35-46b9-98ca-dbf6167aa2ed:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:fda29487-2b1e-4856-8744-bdbc6b27bbb3'
      - 'layoutElement:1438db13-6011-4df4-85c1-14f7ad96cd31'
      - 'layoutElement:b50e0dbf-e560-49f2-8ff4-b496bbfe9db8'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-19T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fda29487-2b1e-4856-8744-bdbc6b27bbb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: creator
            instructions: null
            label: Autor
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1438db13-6011-4df4-85c1-14f7ad96cd31
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-12-19T18:59:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: supplement
            instructions: null
            label: Erg√§nzung
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b50e0dbf-e560-49f2-8ff4-b496bbfe9db8
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: a4ffc8fd-5e3f-4bf6-b0c4-fd10acca4c6f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-19T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2487f4d4-a25f-40aa-8af5-649ebb892d3b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T18:52:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 11f840b0-e02b-470d-8a12-11e80446b819 # SVG Variante
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 673318df-c19b-43b7-aac8-0119d9609bf8
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 9a1f9979-7780-40a7-acac-e99475949a79
        userCondition: null
    thumbFieldKey: null
handle: quote
hasTitleField: false
icon: quotes
name: Zitat
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
