color: null
description: null
fieldLayouts:
  17f3fd21-d01f-4928-85df-b98e973ae2db:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:f7ef4cdd-0fa6-4d24-ac73-328519ac6f75'
      - 'layoutElement:50c9a3ad-fbe8-4f9b-b5f3-9bb14e3ebbb2'
      - 'layoutElement:658ed751-1752-4be6-ba3d-cadc987d47db'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-26T00:36:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: heading
            includeInCards: true
            instructions: null
            label: Ãœberschrift
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7ef4cdd-0fa6-4d24-ac73-328519ac6f75
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:57:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: subtitle
            includeInCards: true
            instructions: null
            label: Untertitel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50c9a3ad-fbe8-4f9b-b5f3-9bb14e3ebbb2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:57:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 658ed751-1752-4be6-ba3d-cadc987d47db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:36:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f76a2dd2-e718-4293-9d3a-13b3db2e26f8 # Team-Mitglied
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bef6e52-a5de-49b7-bdfb-33a0047c14a5
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: eab9ec23-6461-41e4-892f-30fde7167438
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-26T00:36:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a51f6052-0061-40a5-a075-e3a8c9dec111
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:36:26+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11f840b0-e02b-470d-8a12-11e80446b819 # SVG Variante
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1ddb3c0-8fab-40ac-a3c7-a07b14cad186
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 713db6d0-e46a-42b1-ae21-60bf2d5f6a97
        userCondition: null
handle: teamSection
hasTitleField: false
icon: users
name: Team-Sektion
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
