color: null
description: null
fieldLayouts:
  003e9c25-0405-4dc5-8ea6-5dc6151dffe3:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:0336725b-334f-4028-92c4-cf3a4175ed67'
      - 'layoutElement:71b58cba-27d9-401b-b0af-0d1e2c94de42'
      - 'layoutElement:8780bed8-6fd3-42a1-be92-f6582bd1cd32'
      - 'layoutElement:c2b2f738-7286-44ca-959e-0bc10ae3411d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-26T00:27:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: fd3655cc-bfef-4080-87b8-7a02dc9759ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:33:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1696d61-467a-45b3-8386-ec628a918f32 # Bild
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0336725b-334f-4028-92c4-cf3a4175ed67
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:33:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2b2f738-7286-44ca-959e-0bc10ae3411d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:33:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d09b4710-bec0-4a9c-8b18-65fa1b3a880a # E-Mail
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71b58cba-27d9-401b-b0af-0d1e2c94de42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-26T00:33:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c7fd23e2-6f38-4cf9-a791-e8c6719878a7 # Telefon-Nummer
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8780bed8-6fd3-42a1-be92-f6582bd1cd32
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 11ee7c6c-c778-45a9-8344-2783213f0ac7
        userCondition: null
handle: teamMembers
hasTitleField: true
icon: user-large
name: Team-Mitglieder
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
