color: null
description: null
fieldLayouts:
  c0dd29fe-0aca-4a7a-8e21-15bd2c2db137:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:d3ec65f8-355f-42e3-b519-27bef80a6827'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-19T15:51:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 394137d7-b17b-4bf5-9bc2-62dcc5d06808 # Plain Text
            handle: subtitle
            includeInCards: false
            instructions: null
            label: Untertitel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 646b9ea5-dede-41dd-ad55-904be362a0dc
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-19T16:14:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Ãœberschrift
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f57f882-49fc-4b05-a416-dcece485c2fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T16:08:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: description
            includeInCards: false
            instructions: null
            label: Einleitung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e9ad4d4-d87d-49de-a1e3-4c58e6c4a0fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T15:38:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 983f3c7c-a082-4298-bd61-06d175c7cba8 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3ec65f8-355f-42e3-b519-27bef80a6827
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T16:10:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 46dc81ec-70cb-496a-98e9-65e6ca50b3d5 # Link
            handle: button
            includeInCards: false
            instructions: null
            label: Button
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 818e4aab-f3b9-4872-8c60-0ae5c0524476
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b8d78bdd-ae78-485f-9442-7cf21f924570
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-12-19T15:47:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c9288d8-5d14-4d35-b4be-c9cfe19a18bc # Hintergrundfarbe
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35fdbfb8-6e38-49d7-b185-f1d05b26bdd3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T15:55:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f81747ee-8440-434b-9779-936716066903 # Text-Layout
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13727299-d48f-492a-b704-1979a2519005
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-19T15:58:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 11f840b0-e02b-470d-8a12-11e80446b819 # SVG Variante
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25965613-189a-41c6-9852-4503f06cadbd
            userCondition: null
            warning: null
            width: 100
        name: Einstellungen
        uid: 26e60198-0183-4451-865a-956deea4dd18
        userCondition: null
handle: text
hasTitleField: true
icon: text
name: Text
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
