headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Blog Longform'
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
  - '|'
  - createEntry
  - '|'
  - undo
  - redo
