altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0fbf3302-01a1-441f-bccf-82c0722e238e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-25T18:31:15+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d910c661-7e59-45a0-aa6e-19e9f20cb1bf
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 7bff2a26-300e-4f0a-a88d-1b1f5849a9aa
        userCondition: null
fs: images
handle: images
name: Bilder
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
