columnSuffix: null
handle: socialFacebook
instructions: 'Facebook URL'
name: 'Facebook'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
