columnSuffix: null
handle: buttonStyle
instructions: null
name: Button-Stil
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Primär
        -
          - value
          - primary
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Sekundär
        -
          - value
          - secondary
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
