columnSuffix: null
handle: columns
instructions: null
name: Spalten
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - '2'
        -
          - value
          - '2'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3'
        -
          - value
          - '3'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '4'
        -
          - value
          - '4'
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
