columnSuffix: null
handle: contentBuilder
instructions: null
name: 'Content Builder'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 05924f1a-126a-4a36-a9e2-14a56c5c8ccd # Hero
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - c032286b-2d69-4f53-986d-bf92576ecc87 # Text
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - 70ed1bce-64d0-4fdd-86e7-ced980b47160 # Bild und Text
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - 10581733-0aaf-43ac-b04a-9de940b7cf8e # Zitat
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - 2c827773-a1a5-4eec-a293-bbf49f578c99 # Preise-Sektion
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - 6994b292-6925-411a-962d-317554f02c28 # Team-Sektion
        -
          - group
          - Inhalte
    -
      __assoc__:
        -
          - uid
          - 546a1aba-9733-4f5d-917b-567daf653235 # Image Divider
        -
          - group
          - Medien
    -
      __assoc__:
        -
          - uid
          - e295543e-e1d9-41ac-827a-5dd3ba110f60 # Bilder
        -
          - group
          - Medien
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
