columnSuffix: null
handle: socialTwitter
instructions: 'Twitter/X URL'
name: 'Twitter/X'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - url
translationKeyFormat: null
translationMethod: site
type: craft\fields\Link
