columnSuffix: null
handle: featuresTable
instructions: null
name: 'Features Tabelle'
searchable: false
settings:
  addRowLabel: 'Zeile hinzuf√ºgen'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Titel
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - Beschreibung
            -
              - handle
              - description
            -
              - width
              - ''
            -
              - type
              - multiline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
