columnSuffix: null
handle: heroVariant
instructions: null
name: Hero-Variante
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Standard
        -
          - value
          - default
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Gro√ü
        -
          - value
          - large
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
