columnSuffix: null
handle: highlighted
instructions: null
name: 'Highlighted?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
