columnSuffix: null
handle: imageRounding
instructions: null
name: Bild-Rundungen
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Keine
        -
          - value
          - none
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Alle
        -
          - value
          - all
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Oben links und unten rechts'
        -
          - value
          - topLeft-bottomRight
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Oben rechts und unten links'
        -
          - value
          - topRight-bottomLeft
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
