columnSuffix: null
handle: imageOverhang
instructions: null
name: 'Bild-Ãœberhang?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
