columnSuffix: null
handle: layout
instructions: null
name: Layout
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Grid
        -
          - value
          - grid
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Masonry
        -
          - value
          - masonry
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Horizontal
        -
          - value
          - horizontal
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Mixed
        -
          - value
          - mixed
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
