columnSuffix: null
handle: phone
instructions: null
name: Telefon-Nummer
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  types:
    - tel
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
