columnSuffix: null
handle: textAlignment
instructions: null
name: Textausrichtung
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Links
        -
          - value
          - left
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Zentriert
        -
          - value
          - center
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
