columnSuffix: null
handle: textLayout
instructions: null
name: Text-Layout
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Zwei-Spalten
        -
          - value
          - two-column
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Eine Spalte'
        -
          - value
          - one-column
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
