dateModified: 1766719849
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      heading: Inhalt
      key: 'heading:f5588eec-6305-4e52-b765-84658742b58d'
      type: heading
    -
      key: 'section:71b74abe-4015-4367-a552-c9e1667e1cec' # Seiten
      type: native
    -
      heading: Navigation
      key: 'heading:930f4d4a-538a-4c45-a952-0dfd7dd057d4'
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:f33a4e83-1f1c-494a-8868-e03c49695831' # Haupt-Navigation
      tableAttributes:
        - status
        - 'field:46dc81ec-70cb-496a-98e9-65e6ca50b3d5' # Link
      type: native
email:
  fromEmail: hi@thomassausen.com
  fromName: Platypus-Marketing
  transportType: craft\mail\transportadapters\Sendmail
fs:
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    00e38bc0-ae91-4cf8-aa18-0003e2a08d96: Bild-Position # Bild-Position
    2c827773-a1a5-4eec-a293-bbf49f578c99: Preise-Sektion # Preise-Sektion
    3b1d2716-73ff-403e-ac9d-af5e6dda7832: Team-Mitglieder # Team-Mitglieder
    6c9288d8-5d14-4d35-b4be-c9cfe19a18bc: Hintergrundfarbe # Hintergrundfarbe
    6eb230e1-4b05-4189-afed-31ce409f3009: Hero-Variante # Hero-Variante
    11f840b0-e02b-470d-8a12-11e80446b819: 'SVG Variante' # SVG Variante
    23ab57f9-640e-4064-8333-458692667dec: Bilder # Bilder
    27c7e471-18ee-45b7-9b10-b046b53ff4c4: Service # Service
    46dc81ec-70cb-496a-98e9-65e6ca50b3d5: Link # Link
    69e761d0-4b16-45a6-92c3-b605c43e4545: Bilder # Bilder
    70ed1bce-64d0-4fdd-86e7-ced980b47160: 'Bild und Text' # Bild und Text
    71b74abe-4015-4367-a552-c9e1667e1cec: Seiten # Seiten
    73fc6da3-d133-4a74-affd-c06ae2ca7c3c: 'Content Builder' # Content Builder
    381f340a-2f22-4412-b9d1-63971c6a5da9: Service-Farbe # Service-Farbe
    546a1aba-9733-4f5d-917b-567daf653235: 'Image Divider' # Image Divider
    983f3c7c-a082-4298-bd61-06d175c7cba8: Text # Text
    1576f0ec-fbf0-46df-bdf5-c0b9a27c17a5: Spalten # Spalten
    05924f1a-126a-4a36-a9e2-14a56c5c8ccd: Hero # Hero
    6707f2a7-b016-4641-aa2d-165292b7dfb1: Lücke # Lücke
    6994b292-6925-411a-962d-317554f02c28: Team-Sektion # Team-Sektion
    7987c3dc-bd17-4987-a298-02c6dceaf17e: Seiten # Seiten
    74210a0e-fd21-4d35-ad82-89fd1c871a69: Layout # Layout
    394137d7-b17b-4bf5-9bc2-62dcc5d06808: 'Plain Text' # Plain Text
    537187e5-68b5-47b4-92d9-39c5d886ea78: Tiers # Tiers
    02042204-6864-49bf-9cde-1cb1aa18da80: 'Highlighted?' # Highlighted?
    6599081e-7b55-4c7f-8101-8048954a235a: Simple # Simple
    10581733-0aaf-43ac-b04a-9de940b7cf8e: Zitat # Zitat
    54862845-b8ae-4938-a3a9-5f878696acc5: Link # Link
    a7b9b6cf-354d-49e6-995c-14005abaa032: 'Art des Inhalts' # Art des Inhalts
    a38b83cd-7ef0-45ae-9b83-00bd32d1d9ca: Platypus-Marketing # Platypus-Marketing
    acd5ae4b-736e-42bb-b318-c52282d61a09: Bild-Rundungen # Bild-Rundungen
    b591db6f-b83f-4160-ad47-bdfe5b2688e1: Buttons # Buttons
    bb7b9081-dc2c-4665-880e-9668439f22a5: Preis # Preis
    bbbaa0df-d69c-41e2-8fd8-544bbb50f88f: Preise-Reihen # Preise-Reihen
    be9e472f-6557-47cc-8402-06b4027d587b: 'Abgerundet?' # Abgerundet?
    c032286b-2d69-4f53-986d-bf92576ecc87: Text # Text
    c7fd23e2-6f38-4cf9-a791-e8c6719878a7: Telefon-Nummer # Telefon-Nummer
    c64edb66-a3e5-409b-bbd4-1fb8c2eaf0b5: Platypus-Marketing # Platypus-Marketing
    c1696d61-467a-45b3-8386-ec628a918f32: Bild # Bild
    c71043b1-95b7-40c8-9c63-5b63ff1d47f2: Bildhöhe # Bildhöhe
    c748359f-b917-4760-be70-9ce67ca6ce7f: Features # Features
    d09b4710-bec0-4a9c-8b18-65fa1b3a880a: E-Mail # E-Mail
    d9b8121b-ff46-4eb9-bcb7-e0fecf6fdcdc: Button # Button
    d97974b4-1470-4bd7-9ea6-771b4541f465: 'Bild-Überhang?' # Bild-Überhang?
    e295543e-e1d9-41ac-827a-5dd3ba110f60: Bilder # Bilder
    f33a4e83-1f1c-494a-8868-e03c49695831: Haupt-Navigation # Haupt-Navigation
    f76a2dd2-e718-4293-9d3a-13b3db2e26f8: Team-Mitglied # Team-Mitglied
    f81747ee-8440-434b-9779-936716066903: Text-Layout # Text-Layout
    f4296180-a3a3-470e-a6c5-af1f0185be6c: Button-Stil # Button-Stil
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Platypus-Marketing
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
