defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b2c3d4e5-f6a7-4890-b1c2-d3e4f5a6b7c8 # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c64edb66-a3e5-409b-bbd4-1fb8c2eaf0b5: # Platypus
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
