defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b8c9d0e1-f2a3-4456-b789-abcdef012345 # Footer
handle: footer
maxAuthors: 1
name: Footer
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c64edb66-a3e5-409b-bbd4-1fb8c2eaf0b5: # Platypus
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
