defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 54862845-b8ae-4938-a3a9-5f878696acc5 # Link
handle: mainNavigation
maxAuthors: 1
name: Haupt-Navigation
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c64edb66-a3e5-409b-bbd4-1fb8c2eaf0b5: # Platypus-Marketing
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: 9c7c62ce-a9aa-4ae8-8bfb-901e182ca10f
type: structure
