defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7987c3dc-bd17-4987-a298-02c6dceaf17e # Seiten
handle: pages
maxAuthors: 1
name: Seiten
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c64edb66-a3e5-409b-bbd4-1fb8c2eaf0b5: # Platypus-Marketing
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 8f4f34b0-d6a4-416b-9a97-b5612e704003
type: structure
